version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"

    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    depends_on:
      - pgdb
  
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    ports:
      - "5432:5432"
